//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUETallerCrud
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pelicula
    {
        public int id_pelicula { get; set; }

        [Display(Name = "Nombre Película")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido"), MaxLength(55)]
        public string nombre_pelicula { get; set; }

        [Display(Name = "Fecha de Lanzamiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> fecha_lanzamiento { get; set; }

        [Display(Name = "Categoría Película")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La Categoria es requerida"), MaxLength(55)]
        public string categoria { get; set; }

        [Display(Name = "Duración Película (minutos)")]
        [DataType(DataType.Duration)]
        [Required(ErrorMessage = "La duracion de la película es requerida (minutos)")]
        public Nullable<int> duracion { get; set; }
    }
}
